// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var root = Root.FromJson(jsonString);

using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public partial class Root
{
    [JsonProperty("code")]
    public string Code { get; set; }

    [JsonProperty("product")]
    public Product Product { get; set; }

    [JsonProperty("status")]
    public long Status { get; set; }

    [JsonProperty("status_verbose")]
    public string StatusVerbose { get; set; }
}

public partial class Product
    {
        [JsonProperty("_id")]
        public string Id { get; set; }

        [JsonProperty("brands_tags")]
        public string[] BrandsTags { get; set; }

        [JsonProperty("ecoscore_data")]
        public EcoscoreData EcoscoreData { get; set; }

        /* [JsonProperty("ecoscore_grade")]
        public Grade EcoscoreGrade { get; set; }

        [JsonProperty("ecoscore_score")]
        public long EcoscoreScore { get; set; } */

        [JsonProperty("ingredients")]
        public Ingredient[] Ingredients { get; set; }

        [JsonProperty("ingredients_analysis_tags")]
        public string[] IngredientsAnalysisTags { get; set; }

        [JsonProperty("nutriments")]
        public Nutriments Nutriments { get; set; }

        [JsonProperty("nutriscore_grade")]
        public string NutriscoreGrade { get; set; }

        [JsonProperty("product_name")]
        public string ProductName { get; set; }

        [JsonProperty("product_quantity")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long ProductQuantity { get; set; }

        [JsonProperty("product_quantity_unit")]
        public string ProductQuantityUnit { get; set; }
    }

    public partial class EcoscoreData
    {
        [JsonProperty("adjustments")]
        public Adjustments Adjustments { get; set; }

        [JsonProperty("agribalyse")]
        public Agribalyse Agribalyse { get; set; }

        [JsonProperty("grade")]
        public string Grade { get; set; }

        [JsonProperty("grades")]
        public Dictionary<string, string> Grades { get; set; }

        [JsonProperty("missing")]
        public Missing Missing { get; set; }

        [JsonProperty("missing_data_warning")]
        public long MissingDataWarning { get; set; }

        [JsonProperty("score")]
        public long? Score { get; set; }

        [JsonProperty("scores")]
        public Dictionary<string, long> Scores { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }
    }

    public partial class Adjustments
    {
        [JsonProperty("origins_of_ingredients")]
        public OriginsOfIngredients OriginsOfIngredients { get; set; }

        [JsonProperty("packaging")]
        public AdjustmentsPackaging Packaging { get; set; }

        [JsonProperty("production_system")]
        public ProductionSystem ProductionSystem { get; set; }

        [JsonProperty("threatened_species")]
        public ThreatenedSpecies ThreatenedSpecies { get; set; }
    }

    public partial class OriginsOfIngredients
    {
        [JsonProperty("aggregated_origins")]
        public AggregatedOrigin[] AggregatedOrigins { get; set; }

        [JsonProperty("epi_score")]
        public long EpiScore { get; set; }

        [JsonProperty("epi_value")]
        public long EpiValue { get; set; }

        [JsonProperty("origins_from_categories")]
        public string[] OriginsFromCategories { get; set; }

        [JsonProperty("origins_from_origins_field")]
        public string[] OriginsFromOriginsField { get; set; }

        [JsonProperty("transportation_score")]
        public long TransportationScore { get; set; }

        [JsonProperty("transportation_scores")]
        public Dictionary<string, long> TransportationScores { get; set; }

        [JsonProperty("transportation_value")]
        public long TransportationValue { get; set; }

        [JsonProperty("transportation_values")]
        public Dictionary<string, long> TransportationValues { get; set; }

        [JsonProperty("value")]
        public long Value { get; set; }

        [JsonProperty("values")]
        public Dictionary<string, long> Values { get; set; }

        [JsonProperty("warning")]
        public string Warning { get; set; }
    }

    public partial class AggregatedOrigin
    {
        [JsonProperty("epi_score")]
        public long EpiScore { get; set; }

        [JsonProperty("origin")]
        public string Origin { get; set; }

        [JsonProperty("percent")]
        public long Percent { get; set; }

        [JsonProperty("transportation_score")]
        public long TransportationScore { get; set; }
    }

    public partial class AdjustmentsPackaging
    {
        [JsonProperty("non_recyclable_and_non_biodegradable_materials")]
        public long NonRecyclableAndNonBiodegradableMaterials { get; set; }

        [JsonProperty("packagings")]
        public PackagingElement[] Packagings { get; set; }

        [JsonProperty("score")]
        public long Score { get; set; }

        [JsonProperty("value")]
        public long Value { get; set; }

        [JsonProperty("warning")]
        public string Warning { get; set; }
    }

    public partial class PackagingElement
    {
        [JsonProperty("environmental_score_material_score")]
        public long EnvironmentalScoreMaterialScore { get; set; }

        [JsonProperty("environmental_score_shape_ratio")]
        public long EnvironmentalScoreShapeRatio { get; set; }

        [JsonProperty("material")]
        public string Material { get; set; }

        [JsonProperty("number_of_units")]
        public long NumberOfUnits { get; set; }

        [JsonProperty("quantity_per_unit", NullValueHandling = NullValueHandling.Ignore)]
        public string QuantityPerUnit { get; set; }

        [JsonProperty("quantity_per_unit_unit", NullValueHandling = NullValueHandling.Ignore)]
        public string QuantityPerUnitUnit { get; set; }

        [JsonProperty("quantity_per_unit_value", NullValueHandling = NullValueHandling.Ignore)]
        public long? QuantityPerUnitValue { get; set; }

        [JsonProperty("recycling")]
        public string Recycling { get; set; }

        [JsonProperty("shape")]
        public string Shape { get; set; }

        [JsonProperty("weight_measured")]
        public double WeightMeasured { get; set; }
    }

    public partial class ProductionSystem
    {
        [JsonProperty("labels")]
        public object[] Labels { get; set; }

        [JsonProperty("value")]
        public long Value { get; set; }

        [JsonProperty("warning")]
        public string Warning { get; set; }
    }

    public partial class ThreatenedSpecies
    {
        [JsonProperty("ingredient")]
        public string Ingredient { get; set; }

        [JsonProperty("value")]
        public long Value { get; set; }
    }

    public partial class Agribalyse
    {
        [JsonProperty("agribalyse_food_code")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long AgribalyseFoodCode { get; set; }

        [JsonProperty("co2_agriculture")]
        public double Co2Agriculture { get; set; }

        [JsonProperty("co2_consumption")]
        public long Co2Consumption { get; set; }

        [JsonProperty("co2_distribution")]
        public double Co2Distribution { get; set; }

        [JsonProperty("co2_packaging")]
        public double Co2Packaging { get; set; }

        [JsonProperty("co2_processing")]
        public double Co2Processing { get; set; }

        [JsonProperty("co2_total")]
        public double? Co2Total { get; set; }

        [JsonProperty("co2_transportation")]
        public double Co2Transportation { get; set; }

        [JsonProperty("code")]
        [JsonConverter(typeof(ParseStringConverter))]
        public long Code { get; set; }

        [JsonProperty("dqr")]
        public string Dqr { get; set; }

        [JsonProperty("ef_agriculture")]
        public double EfAgriculture { get; set; }

        [JsonProperty("ef_consumption")]
        public long EfConsumption { get; set; }

        [JsonProperty("ef_distribution")]
        public double EfDistribution { get; set; }

        [JsonProperty("ef_packaging")]
        public double EfPackaging { get; set; }

        [JsonProperty("ef_processing")]
        public double EfProcessing { get; set; }

        [JsonProperty("ef_total")]
        public double EfTotal { get; set; }

        [JsonProperty("ef_transportation")]
        public double EfTransportation { get; set; }

        [JsonProperty("is_beverage")]
        public long IsBeverage { get; set; }

        [JsonProperty("name_en")]
        public string NameEn { get; set; }

        [JsonProperty("name_fr")]
        public string NameFr { get; set; }

        [JsonProperty("score")]
        public long Score { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }
    }

    public partial class Missing
    {
        [JsonProperty("labels")]
        public long Labels { get; set; }

        [JsonProperty("origins")]
        public long Origins { get; set; }

        [JsonProperty("packagings")]
        public long Packagings { get; set; }
    }

public partial class Ingredient
{
    [JsonProperty("ciqual_proxy_food_code", NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(ParseStringConverter))]
    public long? CiqualProxyFoodCode { get; set; }

    [JsonProperty("ecobalyse_code", NullValueHandling = NullValueHandling.Ignore)]
    public string EcobalyseCode { get; set; }

    [JsonProperty("id")]
    public string Id { get; set; }

    [JsonProperty("is_in_taxonomy")]
    public long IsInTaxonomy { get; set; }

    [JsonProperty("percent_estimate")]
    public double PercentEstimate { get; set; }

    [JsonProperty("percent_max")]
    public double PercentMax { get; set; }

    [JsonProperty("percent_min")]
    public double PercentMin { get; set; }

    [JsonProperty("text")]
    public string Text { get; set; }

    [JsonProperty("vegan", NullValueHandling = NullValueHandling.Ignore)]
    public string Vegan { get; set; }

    [JsonProperty("vegetarian", NullValueHandling = NullValueHandling.Ignore)]
    public string Vegetarian { get; set; }

    [JsonProperty("ciqual_food_code", NullValueHandling = NullValueHandling.Ignore)]
    [JsonConverter(typeof(ParseStringConverter))]
    public long? CiqualFoodCode { get; set; }

    [JsonProperty("from_palm_oil", NullValueHandling = NullValueHandling.Ignore)]
    public string FromPalmOil { get; set; }
}

public partial class Nutriments
{
    [JsonProperty("carbohydrates")]
    public double Carbohydrates { get; set; }

    [JsonProperty("carbohydrates_100g")]
    public double Carbohydrates100G { get; set; }

    [JsonProperty("carbohydrates_unit")]
    public string CarbohydratesUnit { get; set; }

    [JsonProperty("carbohydrates_value")]
    public double CarbohydratesValue { get; set; }

    [JsonProperty("energy")]
    public double Energy { get; set; }

    [JsonProperty("energy-kcal")]
    public double EnergyKcal { get; set; }

    [JsonProperty("energy-kcal_100g")]
    public double EnergyKcal100G { get; set; }

    [JsonProperty("energy-kcal_unit")]
    public string EnergyKcalUnit { get; set; }

    [JsonProperty("energy-kcal_value")]
    public double EnergyKcalValue { get; set; }

    [JsonProperty("energy-kcal_value_computed")]
    public double EnergyKcalValueComputed { get; set; }

    [JsonProperty("energy_100g")]
    public double Energy100G { get; set; }

    [JsonProperty("energy_unit")]
    public string EnergyUnit { get; set; }

    [JsonProperty("energy_value")]
    public double EnergyValue { get; set; }

    [JsonProperty("fat")]
    public double Fat { get; set; }

    [JsonProperty("fat_100g")]
    public double Fat100G { get; set; }

    [JsonProperty("fat_unit")]
    public string FatUnit { get; set; }

    [JsonProperty("fat_value")]
    public double FatValue { get; set; }

    [JsonProperty("fruits-vegetables-legumes-estimate-from-ingredients_100g")]
    public double FruitsVegetablesLegumesEstimateFromIngredients100G { get; set; }

    [JsonProperty("fruits-vegetables-legumes-estimate-from-ingredients_serving")]
    public double FruitsVegetablesLegumesEstimateFromIngredientsServing { get; set; }

    [JsonProperty("fruits-vegetables-nuts-estimate-from-ingredients_100g")]
    public double FruitsVegetablesNutsEstimateFromIngredients100G { get; set; }

    [JsonProperty("fruits-vegetables-nuts-estimate-from-ingredients_serving")]
    public double FruitsVegetablesNutsEstimateFromIngredientsServing { get; set; }

    [JsonProperty("nova-group")]
    public double NovaGroup { get; set; }

    [JsonProperty("nova-group_100g")]
    public double NovaGroup100G { get; set; }

    [JsonProperty("nova-group_serving")]
    public double NovaGroupServing { get; set; }

    [JsonProperty("nutrition-score-fr")]
    public double NutritionScoreFr { get; set; }

    [JsonProperty("nutrition-score-fr_100g")]
    public double NutritionScoreFr100G { get; set; }

    [JsonProperty("proteins")]
    public double Proteins { get; set; }

    [JsonProperty("proteins_100g")]
    public double Proteins100G { get; set; }

    [JsonProperty("proteins_unit")]
    public string ProteinsUnit { get; set; }

    [JsonProperty("proteins_value")]
    public double ProteinsValue { get; set; }

    [JsonProperty("salt")]
    public double Salt { get; set; }

    [JsonProperty("salt_100g")]
    public double Salt100G { get; set; }

    [JsonProperty("salt_unit")]
    public string SaltUnit { get; set; }

    [JsonProperty("salt_value")]
    public double SaltValue { get; set; }

    [JsonProperty("saturated-fat")]
    public double SaturatedFat { get; set; }

    [JsonProperty("saturated-fat_100g")]
    public double SaturatedFat100G { get; set; }

    [JsonProperty("saturated-fat_unit")]
    public string SaturatedFatUnit { get; set; }

    [JsonProperty("saturated-fat_value")]
    public double SaturatedFatValue { get; set; }

    [JsonProperty("sodium")]
    public double Sodium { get; set; }

    [JsonProperty("sodium_100g")]
    public double Sodium100G { get; set; }

    [JsonProperty("sodium_unit")]
    public string SodiumUnit { get; set; }

    [JsonProperty("sodium_value")]
    public double SodiumValue { get; set; }

    [JsonProperty("sugars")]
    public double Sugars { get; set; }

    [JsonProperty("sugars_100g")]
    public double Sugars100G { get; set; }

    [JsonProperty("sugars_unit")]
    public string SugarsUnit { get; set; }

    [JsonProperty("sugars_value")]
    public double SugarsValue { get; set; }
}



internal class ParseStringConverter : JsonConverter
{
    public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

    public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
    {
        if (reader.TokenType == JsonToken.Null) return null;
        var value = serializer.Deserialize<string>(reader);
        long l;
        if (Int64.TryParse(value, out l))
        {
            return l;
        }
        throw new Exception("Cannot unmarshal type long");
    }

    public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
    {
        if (untypedValue == null)
        {
            serializer.Serialize(writer, null);
            return;
        }
        var value = (long)untypedValue;
        serializer.Serialize(writer, value.ToString());
        return;
    }

    public static readonly ParseStringConverter Singleton = new ParseStringConverter();
}

